export const shopCategories = [
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "home", label: "Home & Furniture" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "toys", label: "Toys & Games" },
  { value: "books", label: "Books & Stationery" },
  { value: "food", label: "Food & Groceries" },
  { value: "health", label: "Health & Wellness" },
  { value: "automotive", label: "Automotive & Tools" },
  { value: "pets", label: "Pet Supplies" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "art", label: "Art & Collectibles" },
  { value: "baby", label: "Baby & Kids" },
  { value: "office", label: "Office Supplies" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "music", label: "Music & Instruments" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "fitness", label: "Fitness Equipment" },
  { value: "party", label: "Party Supplies" },
  { value: "industrial", label: "Industrial Supplies" },
  { value: "crafts", label: "Crafts & Sewing" },
  { value: "digital", label: "Digital Goods" },
  { value: "services", label: "Services" },
  { value: "shoes", label: "Shoes & Footwear" },
  { value: "bags", label: "Bags & Backpacks" },
  { value: "watches", label: "Watches" },
  { value: "glasses", label: "Eyeglasses & Sunglasses" },
  { value: "cosmetics", label: "Cosmetics & Makeup" },
  { value: "skincare", label: "Skincare" },
  { value: "haircare", label: "Hair Care" },
  { value: "fragrances", label: "Perfumes & Fragrances" },
  { value: "men", label: "Men’s Fashion" },
  { value: "women", label: "Women’s Fashion" },
  { value: "kids", label: "Kids’ Fashion" },
  { value: "lingerie", label: "Lingerie & Sleepwear" },
  { value: "swimwear", label: "Swimwear" },
  { value: "formal", label: "Formal Wear" },
  { value: "casual", label: "Casual Wear" },
  { value: "activewear", label: "Activewear" },
  { value: "vintage", label: "Vintage & Retro" },
  { value: "laptops", label: "Laptops & Computers" },
  { value: "phones", label: "Smartphones & Accessories" },
  { value: "cameras", label: "Cameras & Photography" },
  { value: "audio", label: "Audio & Headphones" },
  { value: "tv", label: "TVs & Home Theater" },
  { value: "gaming", label: "Gaming Consoles" },
  { value: "drones", label: "Drones & RC Toys" },
  { value: "smart_home", label: "Smart Home Devices" },
  { value: "wearables", label: "Wearable Tech" },
  { value: "printers", label: "Printers & Scanners" },
  { value: "storage", label: "Storage Devices" },
  { value: "software", label: "Software" },
  { value: "furniture", label: "Furniture" },
  { value: "bedding", label: "Bedding & Linens" },
  { value: "kitchen", label: "Kitchenware" },
  { value: "bath", label: "Bathroom Essentials" },
  { value: "lighting", label: "Lighting" },
  { value: "decor", label: "Home Decor" },
  { value: "appliances", label: "Home Appliances" },
  { value: "cleaning", label: "Cleaning Supplies" },
  { value: "tools", label: "Tools & Hardware" },
  { value: "diy", label: "DIY & Crafting" },
  { value: "outdoor", label: "Outdoor Gear" },
  { value: "camping", label: "Camping Equipment" },
  { value: "fishing", label: "Fishing Gear" },
  { value: "hunting", label: "Hunting Supplies" },
  { value: "cycling", label: "Cycling" },
  { value: "yoga", label: "Yoga & Meditation" },
  { value: "supplements", label: "Vitamins & Supplements" },
  { value: "medical", label: "Medical Supplies" },
  { value: "organic", label: "Organic Products" },
  { value: "vegan", label: "Vegan & Plant-Based" },
  { value: "beverages", label: "Beverages" },
  { value: "snacks", label: "Snacks & Sweets" },
  { value: "baking", label: "Baking Supplies" },
  { value: "spices", label: "Spices & Seasonings" },
  { value: "coffee", label: "Coffee & Tea" },
  { value: "wine", label: "Wine & Spirits" },
  { value: "car_parts", label: "Car Parts" },
  { value: "motorcycle", label: "Motorcycle Gear" },
  { value: "tires", label: "Tires & Wheels" },
  { value: "car_care", label: "Car Care" },
  { value: "dog", label: "Dog Supplies" },
  { value: "cat", label: "Cat Supplies" },
  { value: "fish", label: "Aquarium Supplies" },
  { value: "bird", label: "Bird Supplies" },
  { value: "reptile", label: "Reptile Supplies" },
  { value: "antiques", label: "Antiques" },
  { value: "coins", label: "Coins & Stamps" },
  { value: "memorabilia", label: "Collectibles" },
  { value: "board_games", label: "Board Games" },
  { value: "puzzles", label: "Puzzles" },
  { value: "rc_toys", label: "Remote Control Toys" },
  { value: "dolls", label: "Dolls & Action Figures" },
  { value: "educational", label: "Educational Toys" },
  { value: "tickets", label: "Event Tickets" },
  { value: "experiences", label: "Experiences & Tours" },
  { value: "subscriptions", label: "Subscriptions" },
];
